// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBasDiwbLcQh-tZMiaplKPIol3hTamaVAw',
    appId: '1:618221423421:web:aef563da06bf9b4e961354',
    messagingSenderId: '618221423421',
    projectId: 'korra-9ab95',
    authDomain: 'korra-9ab95.firebaseapp.com',
    storageBucket: 'korra-9ab95.firebasestorage.app',
    measurementId: 'G-TYJG2TWKS6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkHDolChc2tgbBR6mL102FG4nSw0i7vy8',
    appId: '1:618221423421:android:d5f8f0ff64d406e2961354',
    messagingSenderId: '618221423421',
    projectId: 'korra-9ab95',
    storageBucket: 'korra-9ab95.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSg1dG65TX_gMr73Lp9MO93R3mTdbWZSg',
    appId: '1:618221423421:ios:1040628b844eae62961354',
    messagingSenderId: '618221423421',
    projectId: 'korra-9ab95',
    storageBucket: 'korra-9ab95.firebasestorage.app',
    iosBundleId: 'com.example.korra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSg1dG65TX_gMr73Lp9MO93R3mTdbWZSg',
    appId: '1:618221423421:ios:1040628b844eae62961354',
    messagingSenderId: '618221423421',
    projectId: 'korra-9ab95',
    storageBucket: 'korra-9ab95.firebasestorage.app',
    iosBundleId: 'com.example.korra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBasDiwbLcQh-tZMiaplKPIol3hTamaVAw',
    appId: '1:618221423421:web:2383d2c3c40617d6961354',
    messagingSenderId: '618221423421',
    projectId: 'korra-9ab95',
    authDomain: 'korra-9ab95.firebaseapp.com',
    storageBucket: 'korra-9ab95.firebasestorage.app',
    measurementId: 'G-TJPVVV7N14',
  );
}
