// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6uRLryJlwgzu9_EdiIBFQBJHItf8E9a0',
    appId: '1:761341878280:web:fc262ef313f9b7dbbcf1bd',
    messagingSenderId: '761341878280',
    projectId: 'korra-prod-63687',
    authDomain: 'korra-prod-63687.firebaseapp.com',
    storageBucket: 'korra-prod-63687.firebasestorage.app',
    measurementId: 'G-YKXMC6MD2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfVVSU2Kj2oxeVWavJ93mUwnzEdtNePNM',
    appId: '1:761341878280:android:8ee7f32e0fad0feabcf1bd',
    messagingSenderId: '761341878280',
    projectId: 'korra-prod-63687',
    storageBucket: 'korra-prod-63687.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUvplUFu9A0CqGsC9SBgTHGQdCzpCNeq8',
    appId: '1:761341878280:ios:bb1abcc3a09e4225bcf1bd',
    messagingSenderId: '761341878280',
    projectId: 'korra-prod-63687',
    storageBucket: 'korra-prod-63687.firebasestorage.app',
    iosBundleId: 'com.example.korra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUvplUFu9A0CqGsC9SBgTHGQdCzpCNeq8',
    appId: '1:761341878280:ios:bb1abcc3a09e4225bcf1bd',
    messagingSenderId: '761341878280',
    projectId: 'korra-prod-63687',
    storageBucket: 'korra-prod-63687.firebasestorage.app',
    iosBundleId: 'com.example.korra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6uRLryJlwgzu9_EdiIBFQBJHItf8E9a0',
    appId: '1:761341878280:web:194f255df156ab80bcf1bd',
    messagingSenderId: '761341878280',
    projectId: 'korra-prod-63687',
    authDomain: 'korra-prod-63687.firebaseapp.com',
    storageBucket: 'korra-prod-63687.firebasestorage.app',
    measurementId: 'G-B31C451C78',
  );
}
